### PR TITLE
RGB/RBG Flag, Cleanup, Removal of Extra Code

### PR DESCRIPTION
**Pull request by disruptivepatternmaterial**
Hello again!

I merged in your changes that you made yesterday and then merged back in mine.

This code exposes 

1. dump config (and you can see how I use it in my clock yaml)
2. more brightness configs
3. a flag to flip RGB to RBG for the panels that do that (I have both types)

I have pin E panels, that is the next things to test!

### CODE REVIEW

**Comment by sekureco42** [comment]
Hi disruptivepatternmaterial

Thank you again for your suggestions and work on the library. I see from the changes you did that mostly the adaption of "your" panels seems to be an issue. Unfortunately thats "normal" in the HUB75 space - if you check the underlaying library https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA you will see that this is a big topic and is the reason why most of the aspects are configurable (which will be also available in this component due those are exposed as configurable items).

So most of you additions to code could be adressed by proper configuration of your ESPHome project. I try to show you the required configuration according your changes to the code and the file `pins.txt` (note the `pin_` entries):

```
display:
  platform: hub75_default
  id: my_trinity_display
  auto_clear_enabled: true
  pin_r1: 25 # Default: 25
  pin_g1: 27 # Default: 26
  pin_b1: 26 # Default: 27
  pin_r2: 14 # Default: 14
  pin_g2: 13 # Default: 12
  pin_b2: 12 # Default: 13
  pin_a: 23 # Default: 23
  pin_b: 19 # Default: 19
  pin_c: 5 # Default: 5
  pin_d: 17 # Default: 17
  pin_e: 18 # Default: -1
  pin_latch: 4 # Default: 4
  pin_oe: 15 # Default: 15
  pin_clk: 16 # Default: 16
  brightness: 250
  max_brightness: 255
  min_brightness: 0
  #update_interval: 5s
  pages:
  ...
```

To simplify the configuration only the values different from "default" have to be changed and the config file would look even simpler:


```
display:
  platform: hub75_default
  id: my_trinity_display
  auto_clear_enabled: true
  pin_g1: 27 # Default: 26
  pin_b1: 26 # Default: 27
  pin_g2: 13 # Default: 12
  pin_b2: 12 # Default: 13
  pin_e: 18 # Default: -1
  brightness: 250
  max_brightness: 255
  min_brightness: 0
  #update_interval: 5s
  pages:
  ...
```

Your panel should work with a configuration like this without modifying the code. Could you try this and give me a feedback?

Regarding the `brightness` settings: Those are working on my end with the existing code (due the configuration items already existed in the oldest available code). Did you had issues with those settings?

**Comment by disruptivepatternmaterial** [comment]
The brightness ones were not working as coded, which is why I made those changes. I can see about slowly reversing them back out and find the fault when I have some more time. The main thing is that I needed the code to report back the current brightness, which it was not before.

Regarding the pins, yes, all that will work, but that is frankly silly since there are commonly 2 types of panels. I have 100's of these panels in various projects and installations and the all come in 2 configs: one with RGB and one with RBG. So I wanted to make a simple switch, which my next step is to set from ESPHOME so I can make my life even easier and not have to make multiple configs. See when deploying 100's of these things when you have no idea which ones do what until they arrive from China, I'm trying to make it was easy on the end user as possible.

This is pin order config is also how WLED and the RPI Matrix Library from HZeller (--led-rgb-sequence)  work as well; they do not force a bunch of pin config, but instead make flipping these easy and this condition is even mentioned in the FAQ on the trinity page.

Fine with me if your approach differs from mine :) the beauty of forks! It is likely this will be the last PR anyhow because I know my next step is too specific: I want to put into the code the night mode (all red) because it will work better than in the yaml.

**Comment by sekureco42** [comment]
Thank you for your explanations.

Regarding the RGB order I understand your arguments. I do not have that many panels as you have - but according to your experience I would say it is worth to integrate this setting into the component. I will add it later.

The night mode is an interesting feature. To be honest I have a derived component from this component which add this night mode on its own (so I was able to release the base class for others). I'm open to include such a night mode into the base class (this component). A first step could be that at least a flag is exposed in the class so the component would know if it is night or day mode. Even better would be if the component would be able to convert everything which is drawn on its canvas to a shade of red color - but currently I have no clue how to achieve that with minimal effort...

What do you think how to implement this night mode? Probably we open a new PR for that?

cheers,
rOger

**Comment by sekureco42** [comment]
I added support for key `rgb_order: "RBG"` and added a section to the documentation.

**Comment by sekureco42** [comment]
Thank you for sharing the video of your clock - looks nice!

**Comment by disruptivepatternmaterial** [comment]
hahah I should be thanking you!!! You did all the work!!! :)

**Comment by sekureco42** [comment]
Your last change could be also done in your lambda by calling method `void set_brightness(uint8_t brightness)`. I will close this PR.

**Pull request closed without merging**
